language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
env:
  global:
  - secure: vCmILWuQgMJKec2TYXPrxw/ChXrI3QAqVdMBvldCtVT9cXqniiSMcIVVQicwQGPG/2RLF3mPH5L+4U895/Z+OTNXW7Ie11XjhNeZcvnHDEQGlBmXAayqL4ODRnb/+8G4zsPuvq1C9d3U3RR65NIJx3cR+I9DNPBaxSTL8eRW1UXifFbAs10eAVgnBQows/i6VZ8T75L3iqjoLt9Vy5G5vp1qM3U+k/qffX/Lxm4Edmx1uP99PoN+JfmYAcLeeJSBk+gX3S32hXwdhbaNDupxSS0KdgIffs8JXRPC+Xky5IcN1c5n9mJemF3XTgmljpcpBuZFwp3ugymT9gGwQja8P+tyPXIzO/0JCybr2agzwcMMHaFJHRz+5Wf4QeIspLsocm4RTspJ0Lsz2ykM7DiJfvUbVDYeBUHMWNskMOz/Ftoy1uqp2zeVBGqJIf0sAmC+F0FPJ3ugDF+iDHUv/LJ3H1upIWhHYu6/T407i9N86whymyV35rJPgCEaJVc7KwSxlcZWD1uxCD8dFgTsMS9f2x98gHJrrFC0yn7l6YIzv0cZPujV8pdOjRY1Hb0H/hfzGVg4fsn4a/mbwFyj7weroYToOhjr2TwaiENoDjqBU/5hJCfL3T6yLM61DfCUvrCwzCUOU7dZmrlVxId07X6wKcy+g5zBlDS2tFRbcBJfy4I=
  - secure: b/cWiOSPMx7MrgqBw6+f8an6xCXXzSBVsccxw4xRaSVgvcFqpcZbl8aFJH4HKPL5oaw9gnsQZJl9z2BlHAuxJAjLQuvjCPOvuANxxhQI+WY69yMt7GzMUE5Mqs56Y5Wpuk8dq/lwzMNwY0hLMdEmtXz1vmqhlHOghQIhP5OhCha7cfvtxvOx6d7Nzf5+O6iMtqchoH2qvV6ocuVkGuCcBYaeranbAmkpwHtfkqR5r3Aq8JsZaChhWDg7W0VjeoRGwHjcF7G1L/PVoqLRfFas/eUrPzP4fbsu8LZgTCZSJ6b0dXjDfElyR21ptvLtE/hWoF0hv2ko/lqnPwxm3DX4YHXVk2OP44Et0iDvAVi1nDK69HNRDslkvwg/6mZIjNKnmmJ7tXLPx+ahcZpcmGIEVpo6FIF0k7HL2PJQn7luTY7Bh/0/rJIJpdnJi8LEirKNSaBL9neASYP0mPtziA//w7Cf3d+e41SseFWTQZQ6po4MQsuPdaVjJjDK0nJgcqOOnRyo7mCiomuIdxZ7GGUgJ6paWxAA5oi8mFCfkQP2l5DcCp9I0y9MX9NvHJX1FkIPkHK1MzQmYmH2RoGl3VbkFlLhgGHp53AVMbJPJuKzQ+OGT2VpRs/dUB+BppulyKakNxhlDCt/COTvxHYD8iM6IJ0cNeFs8Wae/3aydrYgnR8=
  - COMMIT=${TRAVIS_COMMIT::8}
script: 
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=isaiahsolo/personal-site-frontend
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
